image:
  repository: ghcr.io/blakeblackshear/frigate
  tag: 0.15.1
  pullPolicy: IfNotPresent

env:
  FRIGATE_MQTT_USER: "frigate"
  FRIGATE_MQTT_PASSWORD: "mqtt"
  OPENAI_BASE_URL: "http://10.223.24.242:9766"
  OPENAI_API_KEY: "your_openai_api_key"

persistence:
  enabled: true
  videos:
    enabled: true
    mountPath: /videos
