image:
  repository: ghcr.io/blakeblackshear/frigate
  tag: 0.15.1
  pullPolicy: IfNotPresent

env:
  FRIGATE_MQTT_USER: ""
  FRIGATE_MQTT_PASSWORD: ""
  OPENAI_BASE_URL: ""
  OPENAI_API_KEY: "your_openai_api_key"

persistence:
  enabled: true
  videos:
    enabled: true
    mountPath: /videos
