image:
  repository: intel/nvr-event-router
  tag: 1.2.0

replicaCount: 1

service:
  type: ClusterIP
  port: 8000

env:
  MODE: "backend"
  FRIGATE_BASE_URL: "http://frigate:5000"
  VSS_SEARCH_IP: ""
  VSS_SEARCH_PORT: 12345
  VSS_SUMMARY_IP: ""
  VSS_SUMMARY_PORT: 12345
  no_proxy: ""
  MQTT_USER: "frigate"
  MQTT_PASSWORD: "mqtt"
  REDIS_PORT: 6379
  REDIS_HOST: "redis"
  MQTT_BROKER: "mqtt-broker"
  MQTT_PORT: "1883"


volumes:
  appSrc:
    name: app-src
    hostPath: /home/intel/jsaini/edge-ai-suites/metro-ai-suite/smart-nvr/src
    mountPath: /app/backend
  localtime:
    name: localtime
    hostPath: /etc/localtime
    mountPath: /etc/localtime
    readOnly: true
