global:
  # pvcName is the name of common PVC used by multiple microservices for persisting models, cache and other files.
  pvcName: ""
  # claimSize is the size of the PVC to be created.
  claimSize: "50Gi"  
  # keepPvc should be set to true to retain the PVC after uninstalling the chart.
  keepPvc: false

  proxy:
    no_proxy: "localhost,127.0.0.1,192.168.0.0/16,172.16.0.0/12,127.0.0.0/8,10.0.0.0/8,.svc.cluster.local,10.223.24.242"
    http_proxy: "http://proxy-pilot.intel.com:916"
    https_proxy: "http://proxy-pilot.intel.com:916"

frigate:
  image:
    repository: ghcr.io/blakeblackshear/frigate
    tag: stable

# nvr-event-router:
#   image:
#     repository: intel/nvr-event-router
#     tag: 1.2.0
#   env:
#     MODE: "backend"
#     FRIGATE_BASE_URL: "http://frigate:5000"
#     VSS_SEARCH_URL: "http://search:8000"
#     VSS_SUMMARY_URL: "http://summary:8000"
#     MQTT_USER: "admin"
#     MQTT_PASSWORD: "admin"
#     HOST_IP: "127.0.0.1"

nvr-event-router-ui:
  image:
    repository: intel/nvr-event-router
    tag: 1.2.0
  env:
    MODE: "ui"
    API_BASE_URL: "http://nvr-event-router:8000"
    EVENT_POLL_INTERVAL: "3000"
    NVR_GENAI: "true"

mqtt-broker:
  image:
    repository: eclipse-mosquitto
    tag: 2.0
  env:
    MQTT_USER: "frigate"
    MQTT_PASSWORD: "mqtt"

redis:
  image:
    repository: redis
    tag: 7.0