apiVersion: v1
kind: Service
metadata:
  name: nvr-event-router-ui
spec:
  selector:
    app: nvr-event-router-ui
  ports:
    - protocol: TCP
      port: {{ .Values.service.port }}
      targetPort: 7860
  type: {{ .Values.service.type }}
