apiVersion: apps/v1
kind: Deployment
metadata:
  name: nvr-event-router
  labels:
    app: nvr-event-router
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: nvr-event-router
  template:
    metadata:
      labels:
        app: nvr-event-router
    spec:
      containers:
        - name: nvr-event-router
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          ports:
            - containerPort: 8000
          env:
            - name: MODE
              value: "{{ .Values.env.MODE }}"
            - name: FRIGATE_BASE_URL
              value: "{{ .Values.env.FRIGATE_BASE_URL }}"
            - name: VSS_SEARCH_URL
              value: "{{ .Values.env.VSS_SEARCH_URL }}"
            - name: VSS_SUMMARY_URL
              value: "{{ .Values.env.VSS_SUMMARY_URL }}"
            - name: no_proxy
              value: "{{ .Values.env.no_proxy }}"
            - name: MQTT_USER
              value: "{{ .Values.env.MQTT_USER }}"
            - name: MQTT_PASSWORD
              value: "{{ .Values.env.MQTT_PASSWORD }}"
            - name: REDIS_PORT
              value: "{{ .Values.env.REDIS_PORT }}"
            - name: REDIS_HOST
              value: "{{ .Values.env.REDIS_HOST }}"
            - name: MQTT_BROKER
              value: "{{ .Values.env.MQTT_BROKER }}"   # Kubernetes service name
            - name: MQTT_PORT
              value: "{{ .Values.env.MQTT_PORT }}"         # Default Mosquitto port

          volumeMounts:
            - name: {{ .Values.volumes.localtime.name }}
              mountPath: {{ .Values.volumes.localtime.mountPath }}
              readOnly: {{ .Values.volumes.localtime.readOnly }}

      volumes:
        - name: {{ .Values.volumes.localtime.name }}
          hostPath:
            path: {{ .Values.volumes.localtime.hostPath }}
