apiVersion: v1
kind: Service
metadata:
  name: nvr-event-router
spec:
  selector:
    app: nvr-event-router
  ports:
    - protocol: TCP
      port: {{ .Values.service.port }}
      targetPort: 8000
  type: {{ .Values.service.type }}
