apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: resources-pvc
  namespace: nvr
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: longhorn  # change this according to your cluster
